### ISSUE TITLE
Problems with the web server: 302 Found

### ISSUE THREAD

**Issue by zhang-jiankun** [EnsemblGenomes/eg-biomart-perl#16]
```
Processing Cached Registry: /share/home/zhangjk/software/biomart-perl/conf/cachedRegistries/martURLLocation.xml.cached
Problems with the web server: 302 Found
```
Why I got this with nearly the same code?

**Comment by wbazant** [comment]
Hello! I don't know. BioMart is not supported, and Ensembl are trying to get rid of it. What are you trying to do?

**Comment by zhang-jiankun** [comment]
I want to write a script that can get information such as the transcription start site of genes from online database. Some R packages are not powerful enough.

**Comment by wbazant** [comment]
There's the https://bioconductor.org/packages/release/bioc/html/biomaRt.html biomaRt package, which I have never used but the legends say it is as powerful as biomart itself.

There are also APIs : https://rest.ensembl.org/

**Comment by zhang-jiankun** [comment]
Thanks for the help! I will give it a try.
