### ISSUE TITLE
Columns randomly ordered when using URL to access saved results

### ISSUE THREAD

**Issue by creinkin** [EnsemblGenomes/eg-biomart-perl#8]
When using the URL button to create a permalink for the results set, the URL matches the column display order on the results list.

When using that URL to access the results, the column order is not preserved, but is ordered 'randomly' because they are stored in a hash and iterated over as keys. For example, in VectorBase's instance of biomart-perl, the results like this:

![image](https://cloud.githubusercontent.com/assets/10441248/8133208/e7014f22-10f4-11e5-854c-8ed684bcf350.png)

will result in this URL: http://biomart.pre.vectorbase.org/biomart/martview?VIRTUALSCHEMANAME=vb_mart_1506&ATTRIBUTES=agambiae_eg_gene.default.feature_page.ensembl_gene_id|agambiae_eg_gene.default.feature_page.ensembl_transcript_id|agambiae_eg_gene.default.feature_page.transmembrane_domain|agambiae_eg_gene.default.feature_page.signal_domain|agambiae_eg_gene.default.feature_page.ncoils&FILTERS=agambiae_eg_gene.default.filters.ensembl_gene_id."AGAP001432,AGAP001565,AGAP001733,AGAP002712,AGAP003702,AGAP003703,AGAP005351,AGAP005817,AGAP007508,AGAP007706,AGAP007826,AGAP010177,AGAP010715,AGAP011124,AGAP011219,AGAP011289,AGAP011757"&VISIBLEPANEL=resultspanel

Copy, pasting that into a new browser tab yields this output (notice the change in column order):
![image](https://cloud.githubusercontent.com/assets/10441248/8133227/0ca8ac3e-10f5-11e5-8e2c-afe131610e4c.png)

I have hacked together a patch for this and will submit a pull request for review and testing, but basically my solution was to convert the attributes hash into a list that could be iterated over in a predictable order.

CAVEAT: I am not by any means a perl programmer or expert in the biomart-perl codebase so feel free to let me know if the patch horribly breaks biomart. We have been using the patch on VectorBase for some time now with no known consequences

**Comment by james-monkeyshines** [comment]
Merged.
